# ByteHot Kubernetes Deployment - Secrets
# Sensitive configuration for ByteHot applications

apiVersion: v1
kind: Secret
metadata:
  name: bytehot-secrets
  namespace: bytehot
  labels:
    app.kubernetes.io/name: bytehot
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: bytehot-platform
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_USERNAME: Ynl0ZWhvdA==  # bytehot
  DB_PASSWORD: Ynl0ZWhvdDEyMw==  # bytehot123
  
  # Redis password (base64 encoded)
  REDIS_PASSWORD: cmVkaXNfcGFzcw==  # redis_pass
  
  # ByteHot security keys (base64 encoded)
  BYTEHOT_SIGNATURE_KEY: c2VjcmV0X3NpZ25hdHVyZV9rZXk=  # secret_signature_key
  BYTEHOT_ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfMTIzNDU=  # encryption_key_12345

---
apiVersion: v1
kind: Secret
metadata:
  name: bytehot-tls
  namespace: bytehot
  labels:
    app.kubernetes.io/name: bytehot
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: bytehot-platform
type: kubernetes.io/tls
data:
  # TLS certificate for HTTPS (dummy data - replace with real certificates)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLi4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLi4KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==