# ByteHot Kubernetes Deployment - Service Account and RBAC
# Service account with permissions for ByteHot operations

apiVersion: v1
kind: ServiceAccount
metadata:
  name: bytehot-service-account
  namespace: bytehot
  labels:
    app.kubernetes.io/name: bytehot
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: bytehot-platform
  annotations:
    bytehot.org/permissions: "hot-swap,monitoring,logging"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bytehot-role
  namespace: bytehot
  labels:
    app.kubernetes.io/name: bytehot
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: bytehot-platform
rules:
  # Pod operations for hot-swap coordination
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
    
  # ConfigMap operations for configuration hot-swapping
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
    
  # Secret operations (read-only)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
    
  # Service operations for discovery
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
    
  # Event operations for hot-swap notifications
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bytehot-role-binding
  namespace: bytehot
  labels:
    app.kubernetes.io/name: bytehot
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: bytehot-platform
subjects:
  - kind: ServiceAccount
    name: bytehot-service-account
    namespace: bytehot
roleRef:
  kind: Role
  name: bytehot-role
  apiGroup: rbac.authorization.k8s.io

---
# Cluster-level permissions for cross-namespace operations (optional)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bytehot-cluster-role
  labels:
    app.kubernetes.io/name: bytehot
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: bytehot-platform
rules:
  # Node information for deployment decisions
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
    
  # Namespace operations for multi-namespace deployments
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
    
  # Custom resource operations for ByteHot CRDs
  - apiGroups: ["bytehot.org"]
    resources: ["hotswapdeployments", "hotswapconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bytehot-cluster-role-binding
  labels:
    app.kubernetes.io/name: bytehot
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: bytehot-platform
subjects:
  - kind: ServiceAccount
    name: bytehot-service-account
    namespace: bytehot
roleRef:
  kind: ClusterRole
  name: bytehot-cluster-role
  apiGroup: rbac.authorization.k8s.io