# ByteHot E-Commerce Example Application Configuration
spring:
  application:
    name: bytehot-ecommerce-example
  
  # Database Configuration (H2 for simplicity)
  datasource:
    url: jdbc:h2:mem:ecommerce
    driverClassName: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # Cache Configuration
  cache:
    type: simple
    cache-names:
      - products
      - pricing
      
  # Actuator Configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,bytehot
    endpoint:
      health:
        show-details: always
        
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /ecommerce

# Logging Configuration
logging:
  level:
    org.acmsl.bytehot.examples: INFO
    org.acmsl.bytehot: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ByteHot Configuration
bytehot:
  enabled: true
  config:
    watch-paths:
      - src/main/java/org/acmsl/bytehot/examples/ecommerce/service
      - src/main/java/org/acmsl/bytehot/examples/ecommerce/controller
    hot-swap:
      enabled: true
      auto-reload: true
    monitoring:
      enabled: true
      metrics-export: true
    production:
      error-handling:
        enabled: true
        circuit-breaker: true
      performance-monitoring: true
      resource-optimization: true

# Application-specific Configuration
ecommerce:
  products:
    low-stock-threshold: 10
    max-search-results: 100
  pricing:
    enable-dynamic-pricing: true
    enable-time-based-pricing: true
    max-discount-percentage: 30
  cache:
    product-ttl: 300  # 5 minutes
    pricing-ttl: 60   # 1 minute