name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [17]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Verify Maven configuration
      run: |
        echo "=== Maven version ==="
        mvn --version
        echo "=== Java version ==="
        java -version
        echo "=== Project structure ==="
        find . -name "pom.xml" -type f
        
    - name: Build project (install all modules)
      run: mvn clean install -DskipTests -B
      
    - name: Verify agent JAR exists
      run: |
        echo "=== Checking for agent JAR ==="
        find . -name "*agent.jar" -type f
        echo "=== Directory structure ==="
        ls -la */target/ || echo "No target directories found"
        
    - name: Run tests
      run: mvn test -B
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: '**/target/surefire-reports/*.xml'
        reporter: java-junit
        fail-on-error: true
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-java-${{ matrix.java-version }}
        path: |
          **/target/surefire-reports/
          **/target/site/
          
    - name: Check for security vulnerabilities
      run: mvn org.owasp:dependency-check-maven:check -B
      continue-on-error: true
      
    - name: Upload OWASP report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: owasp-report
        path: '**/target/dependency-check-report.html'
        
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Run SpotBugs analysis
      run: mvn spotbugs:check -B
      continue-on-error: true
      
    - name: Run PMD analysis
      run: mvn pmd:check -B
      continue-on-error: true
      
    - name: Upload code quality reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-quality-reports
        path: |
          **/target/spotbugsXml.xml
          **/target/pmd.xml