name: Pages Health Check

on:
  schedule:
    # Check pages health every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh
        
      - name: Execute pages health check
        run: .github/scripts/pages-health-check.sh
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}